;; Generated by maven-jdee-plugin version 1.2.2
;; Don't make any changes in this file.
(jde-project-file-version "1.2.2")
(jde-set-variables
  '(jde-project-name "maven-emacs-plugin-test")
  '(jde-project-file-name "prj.el")

  '(jde-sourcepath '("/home/benzin/work/java/maven-emacs-plugin/src/test/java" "/home/benzin/work/java/maven-emacs-plugin/src/main/java"))
  '(jde-compile-option-directory "/home/benzin/work/java/maven-emacs-plugin/target/test-classes")
  '(jde-global-classpath '(
    "/home/benzin/work/java/maven-emacs-plugin/target/test-classes"
    "/home/benzin/work/java/maven-emacs-plugin/target/classes"
    "/home/benzin/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-alpha-6/wagon-provider-api-1.0-alpha-6.jar"
    "/home/benzin/.m2/repository/org/apache/maven/maven-profile/2.0.4/maven-profile-2.0.4.jar"
    "/home/benzin/.m2/repository/org/apache/maven/maven-project/2.0.4/maven-project-2.0.4.jar"
    "/home/benzin/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.4/maven-repository-metadata-2.0.4.jar"
    "/home/benzin/.m2/repository/org/codehaus/plexus/plexus-container-default/1.0-alpha-9/plexus-container-default-1.0-alpha-9.jar"
    "/home/benzin/.m2/repository/org/codehaus/plexus/plexus-utils/1.4.2/plexus-utils-1.4.2.jar"
    "/home/benzin/.m2/repository/org/apache/maven/maven-artifact-manager/2.0.4/maven-artifact-manager-2.0.4.jar"
    "/home/benzin/.m2/repository/org/apache/maven/maven-plugin-api/2.0.4/maven-plugin-api-2.0.4.jar"
    "/home/benzin/.m2/repository/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar"
    "/opt/sun-jdk-1.6.0.03/jre/../lib/tools.jar"
    "/home/benzin/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar"
    "/home/benzin/.m2/repository/org/apache/maven/maven-artifact/2.0.4/maven-artifact-2.0.4.jar"
    "/home/benzin/.m2/repository/org/apache/maven/maven-model/2.0.4/maven-model-2.0.4.jar"
    "/home/benzin/.m2/repository/org/apache/maven/maven-settings/2.0.4/maven-settings-2.0.4.jar"
))

  '(jde-help-docsets (append '(
    ("User (javadoc)" "/home/benzin/.m2/cache/org.apache.maven/maven-project/2.0.4/javadoc" nil)
    ("User (javadoc)" "/home/benzin/.m2/cache/org.codehaus.plexus/plexus-utils/1.4.2/javadoc" nil)
    ("User (javadoc)" "/home/benzin/.m2/cache/org.apache.maven/maven-plugin-api/2.0.4/javadoc" nil)
    ("User (javadoc)" "/home/benzin/.m2/cache/junit/junit/3.8.1/javadoc" nil)
    ("User (javadoc)" "/home/benzin/.m2/cache/org.apache.maven/maven-artifact/2.0.4/javadoc" nil)
) jde-global-help-docsets))
)

(setq jde-maven-project-file-name "/home/benzin/work/java/maven-emacs-plugin/pom.xml")

(setq jde-checkstyle-style "config/maven_checks.xml")

(jde-maven2-set-current-goal
  (if (jde-maven2-get-goal) (jde-maven2-get-goal) "surefire:test"))


(jde-maven2-recreate-project-file-if-change "1.2.2" "-DglobalCachePath=/home/benzin/.m2/cache" "-DdefaultGoal=install" "-DtestGoal=surefire:test" )
